### ISSUE TITLE
`client.select_items_data` without clear alternative

### ISSUE THREAD

**Issue by astrojuanlu** [clarify/pyclarify#105]
I'm running the Email notifications tutorial and noticed that `client.select_items_data` emits a `DeprecationWarning` saying "Use select_items() with include_metadata=False instead.". However, `select_items` has no `ids` parameter, and it's not evident to me how to do the replacement:

https://github.com/clarify/pyclarify/blob/dc9319aa9148d930aa3e3bc22a154e6f7ec3c5d4/src/pyclarify/client.py#L845-L855

It's probably trivial but maybe it would be worth adding a example to the (already quite nice) docstring, or even to the `DeprecationWarning` itself?

At the moment, what I'm doing instead is fetching the whole dataset and then extracting the column that corresponds to my `item_id`(s) of interest.

**Comment by oddaspa** [comment]
Hello @astrojuanlu !

We are moving away from custom methods, and want to use a more general filter to do querying in the future. We have not updated the docs yet, but there is an example of how to use filters in the [CHANGELOG](https://github.com/clarify/pyclarify/blob/main/CHANGELOG.md). More specifically for your case, here is a way to achieve the same with the new `select_items` method:

```python
from pyclarify import ClarifyClient
from pyclarify import query

client = ClarifyClient("clarify-credentials.json")

filter = query.Filter(fields={"id": query.In(value=["<ID OF AN ITEM>", "<ID OF AN ITEM>"])})
response = client.select_items(filter=filter, include_metadata=False)
```

**Comment by astrojuanlu** [comment]
Thanks @oddaspa for the quick response! I just tried it and it works. Feel free to leave this issue open or close it whenever you decide.

**Comment by oddaspa** [comment]
Update for you @astrojuanlu !

We have updated our tutorials for PyClarify to the newest version and added [a filter section](https://colab.research.google.com/github/clarify/data-science-tutorials/blob/main/tutorials/Introduction.ipynb#scrollTo=9a3df0e1). I hope this makes the filtering system clear.

**Comment by astrojuanlu** [comment]
This is excellent, thanks a lot! I'm proceeding to close this 💪🏽
