### ISSUE TITLE
Item model should not have a type attribute

### ISSUE THREAD

**Issue by AlexiaArtemis** [clarify/pyclarify#110]
The error that I got is 

```jsonrpc='2.0' id='1' result=None error=Error(code='-32602', message='Invalid params', data=ErrorData(trace='e18264928fb5ec63546280e9107f1b8a', params={'itemsBySignal': ['json: unknown field "type"']}))```

When I tried to publish a signal
```python
item = Item(name = "test",  visible=True)         
client.publish_signals(signal_ids = ["<signal-id>"], items=[item])
...
```

I changed the [item model ](https://github.com/clarify/pyclarify/blob/d87f3e54c56e082cfee7e872d8086d2abd1db06c/src/pyclarify/models/data.py#L189)to: 

```
class Item(BaseModel):
    visible: bool = False
    name: str
    description: str = ""
    labels: Dict[LabelsKey, List[str]] = {}
    annotations: Optional[Dict[AnnotationKey, str]] = {}
    engUnit: str = ""
    enumValues: Dict[str, str] = {}
    sourceType: SourceTypeSignal = SourceTypeSignal.measurement
    sampleInterval: timedelta = None
    gapDetection: timedelta = None

    class Config:
        json_encoders = {timedelta: timedelta_isoformat}
        extra = Extra.forbid
```

and it worked, without the ```type: TypeSignal = TypeSignal.numeric``` which the [SignalInfo](https://github.com/clarify/pyclarify/blob/d87f3e54c56e082cfee7e872d8086d2abd1db06c/src/pyclarify/models/data.py#L162) has.

**Comment by oddaspa** [comment]
Fixed in #121
