### ISSUE TITLE
Implement omit_empty flag for data_set method

### ISSUE THREAD

**Issue by sarzhann** [clarify/pyclarify#140]
It would be useful to have an additional parameter under [data_set](https://joaquinamatrodrigo.github.io/skforecast/0.4.3/notebooks/forecaster-in-production.html) method like `omit_empty`, which allows keeping rows with empty data so we can have stable window buckets in the data frame.
The use case is easier handling of missing values by data scientists (no need to re-create empty rows manually).
`omit_empty` can be `True` by default for backward compatibility.

**Comment by oddaspa** [comment]
This problem is considered a data science problem and will not be solved in the SDK.
