### ISSUE TITLE
Response type for select_signals request

### ISSUE THREAD

**Issue by AlexiaArtemis** [clarify/pyclarify#77]
**Response type is either SelectSignalsResponse or SelectItemsResponse depending if include signal is True or False**

**To Reproduce**
```python
signals= {"include": False}
items= {"include": True}

params = {"signals": signals, "items": items}

client.select_signals(params)
```

**Expected behavior**
Have only SelectSignalsResponse as response type.

**Quick fix**
Change the order of [response types](https://github.com/clarify/pyclarify/blob/f49c77f89fdb3896bc77586bff2ce9c98c2c8e08/src/pyclarify/models/response.py#L56):
```python
class Response(GenericResponse, extra=Extra.forbid):
    result: Optional[
        Union[
            InsertResponse,
            SaveSignalsResponse,
            SelectSignalsResponse,  # Put before SelectItemsResponse
            SelectItemsResponse,
            PublishSignalsResponse,
        ]
    ]
```

**Comment by AlexiaArtemis** [comment]
This has also an effect in the `select_items_metadata` method.

**Comment by AlexiaArtemis** [comment]
Because of merge conflicts the changes in #78 the suggested changes (see quick fix 👆)  were not applied.

**Comment by oddaspa** [comment]
API version `1.1beta2` always includes signals when calling `admin.SelectSignals` thus eliminating this issue.
